<?php

/**
 * This is the model base class for the table "menu_sub".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MenuSub".
 *
 * Columns in table "menu_sub" available as properties of the model,
 * followed by relations of table "menu_sub" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $link
 * @property string $content
 * @property integer $menu_id
 * @property string $show
 * @property string $order_no
 * @property string $widget
 *
 * @property Menu $menu
 * @property MenuSubTranslate[] $menuSubTranslates
 */
abstract class BaseMenuSub extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'menu_sub';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name, menu_id, show', 'required'),
            array('menu_id', 'numerical', 'integerOnly'=>true),
            array('name, link, widget', 'length', 'max'=>255),
            array('show', 'length', 'max'=>3),
            array('order_no', 'length', 'max'=>5),
            array('content', 'safe'),
            array('link, content, order_no, widget', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, link, content, menu_id, show, order_no, widget', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'menu' => array(self::BELONGS_TO, 'Menu', 'menu_id'),
            'menuSubTranslates' => array(self::HAS_MANY, 'MenuSubTranslate', 'menu_sub_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Name'),
                'link' => Yii::t('app', 'Link'),
                'content' => Yii::t('app', 'Content'),
                'menu_id' => Yii::t('app', 'Menu'),
                'show' => Yii::t('app', 'Show'),
                'order_no' => Yii::t('app', 'Order No'),
                'widget' => Yii::t('app', 'Widget'),
                'menu' => null,
                'menuSubTranslates' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('link', $this->link, true);
        $criteria->compare('content', $this->content, true);
        $criteria->compare('menu_id', $this->menu_id);
        $criteria->compare('show', $this->show, true);
        $criteria->compare('order_no', $this->order_no, true);
        $criteria->compare('widget', $this->widget, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}