<?php

/**
 * This is the model base class for the table "publish".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Publish".
 *
 * Columns in table "publish" available as properties of the model,
 * followed by relations of table "publish" available as properties of the model.
 *
 * @property integer $id
 * @property string $start_date
 * @property string $end_date
 * @property string $payment_status
 * @property integer $job_content_id
 * @property integer $invoice_id
 *
 * @property Invoice $invoice
 * @property JobContent $jobContent
 */
abstract class BasePublish extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'publish';
    }

    public static function representingColumn() {
        return 'start_date';
    }

    public function rules() {
        return array(
            array('start_date, end_date, payment_status, job_content_id', 'required'),
            array('job_content_id, invoice_id', 'numerical', 'integerOnly'=>true),
            array('payment_status', 'length', 'max'=>9),
            array('invoice_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, start_date, end_date, payment_status, job_content_id, invoice_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'invoice' => array(self::BELONGS_TO, 'Invoice', 'invoice_id'),
            'jobContent' => array(self::BELONGS_TO, 'JobContent', 'job_content_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'start_date' => Yii::t('app', 'Start Date'),
                'end_date' => Yii::t('app', 'End Date'),
                'payment_status' => Yii::t('app', 'Payment Status'),
                'job_content_id' => Yii::t('app', 'Job Content'),
                'invoice_id' => Yii::t('app', 'Invoice'),
                'invoice' => null,
                'jobContent' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('start_date', $this->start_date, true);
        $criteria->compare('end_date', $this->end_date, true);
        $criteria->compare('payment_status', $this->payment_status, true);
        $criteria->compare('job_content_id', $this->job_content_id);
        $criteria->compare('invoice_id', $this->invoice_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}