<?php

/**
 * This is the model base class for the table "country".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Country".
 *
 * Columns in table "country" available as properties of the model,
 * followed by relations of table "country" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 *
 * @property Cv[] $cvs
 * @property Cv[] $cvs1
 */
abstract class BaseCountry extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'country';
    }

    public static function representingColumn() {
        return 'code';
    }

    public function rules() {
        return array(
            array('code, name', 'required'),
            array('code, name', 'length', 'max'=>45),
            array('id, code, name', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cvs' => array(self::HAS_MANY, 'Cv', 'country_id'),
            'cvs1' => array(self::HAS_MANY, 'Cv', 'graduated_country_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'code' => Yii::t('app', 'Code'),
                'name' => Yii::t('app', 'Name'),
                'cvs' => null,
                'cvs1' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('code', $this->code, true);
        $criteria->compare('name', $this->name, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}