<?php

/**
 * This is the model base class for the table "job_content_translate".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobContentTranslate".
 *
 * Columns in table "job_content_translate" available as properties of the model,
 * followed by relations of table "job_content_translate" available as properties of the model.
 *
 * @property string $tranlate
 * @property integer $job_content_id
 * @property integer $language_id
 *
 * @property JobContent $jobContent
 * @property Language $language
 */
abstract class BaseJobContentTranslate extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'job_content_translate';
    }

    public static function representingColumn() {
        return 'tranlate';
    }

    public function rules() {
        return array(
            array('tranlate, job_content_id, language_id', 'required'),
            array('job_content_id, language_id', 'numerical', 'integerOnly'=>true),
            array('tranlate, job_content_id, language_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'jobContent' => array(self::BELONGS_TO, 'JobContent', 'job_content_id'),
            'language' => array(self::BELONGS_TO, 'Language', 'language_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'tranlate' => Yii::t('app', 'Tranlate'),
                'job_content_id' => Yii::t('app', 'Job Content'),
                'language_id' => Yii::t('app', 'Language'),
                'jobContent' => null,
                'language' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('tranlate', $this->tranlate, true);
        $criteria->compare('job_content_id', $this->job_content_id);
        $criteria->compare('language_id', $this->language_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}