<?php

/**
 * This is the model base class for the table "language".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Language".
 *
 * Columns in table "language" available as properties of the model,
 * followed by relations of table "language" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $used
 *
 * @property JobContentTranslate[] $jobContentTranslates
 * @property MenuSubTranslate[] $menuSubTranslates
 * @property MenuTranslate[] $menuTranslates
 */
abstract class BaseLanguage extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'language';
    }

    public static function representingColumn() {
        return 'code';
    }

    public function rules() {
        return array(
            array('code, name, used', 'required'),
            array('code, name', 'length', 'max'=>255),
            array('used', 'length', 'max'=>3),
            array('id, code, name, used', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'jobContentTranslates' => array(self::HAS_MANY, 'JobContentTranslate', 'language_id'),
            'menuSubTranslates' => array(self::HAS_MANY, 'MenuSubTranslate', 'language_id'),
            'menuTranslates' => array(self::HAS_MANY, 'MenuTranslate', 'language_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'code' => Yii::t('app', 'Code'),
                'name' => Yii::t('app', 'Name'),
                'used' => Yii::t('app', 'Used'),
                'jobContentTranslates' => null,
                'menuSubTranslates' => null,
                'menuTranslates' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('code', $this->code, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('used', $this->used, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}