<?php

/**
 * This is the model base class for the table "highest_edu_level".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HighestEduLevel".
 *
 * Columns in table "highest_edu_level" available as properties of the model,
 * followed by relations of table "highest_edu_level" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Cv[] $cvs
 */
abstract class BaseHighestEduLevel extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'highest_edu_level';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name', 'required'),
            array('name', 'length', 'max'=>255),
            array('id, name', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cvs' => array(self::HAS_MANY, 'Cv', 'highest_edu_level_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Name'),
                'cvs' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}