<?php

/**
 * This is the model base class for the table "cv_attach_file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CvAttachFile".
 *
 * Columns in table "cv_attach_file" available as properties of the model,
 * followed by relations of table "cv_attach_file" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $cv_id
 *
 * @property Cv $cv
 */
abstract class BaseCvAttachFile extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cv_attach_file';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name, cv_id', 'required'),
            array('cv_id', 'numerical', 'integerOnly'=>true),
            array('name', 'length', 'max'=>255),
            array('id, name, cv_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cv' => array(self::BELONGS_TO, 'Cv', 'cv_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Name'),
                'cv_id' => Yii::t('app', 'Cv'),
                'cv' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('cv_id', $this->cv_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}