<?php

/**
 * This is the model base class for the table "company_has_job_industry".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyHasJobIndustry".
 *
 * Columns in table "company_has_job_industry" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $company_id
 * @property integer $job_industry_id
 *
 */
abstract class BaseCompanyHasJobIndustry extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'company_has_job_industry';
    }

    public static function representingColumn() {
        return array(
            'company_id',
            'job_industry_id',
        );
    }

    public function rules() {
        return array(
            array('company_id, job_industry_id', 'required'),
            array('company_id, job_industry_id', 'numerical', 'integerOnly'=>true),
            array('company_id, job_industry_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'company_id' => Yii::t('app', 'Company'),
                'job_industry_id' => Yii::t('app', 'Job Industry'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('company_id', $this->company_id);
        $criteria->compare('job_industry_id', $this->job_industry_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}