<?php

/**
 * This is the model base class for the table "job_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "JobType".
 *
 * Columns in table "job_type" available as properties of the model,
 * followed by relations of table "job_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $type_description_en
 *
 * @property JobContent[] $jobContents
 */
abstract class BaseJobType extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'job_type';
    }

    public static function representingColumn() {
        return 'type_description_en';
    }

    public function rules() {
        return array(
            array('type_description_en', 'required'),
            array('type_description_en', 'length', 'max'=>255),
            array('id, type_description_en', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'jobContents' => array(self::HAS_MANY, 'JobContent', 'job_type_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'type_description_en' => Yii::t('app', 'Type Description En'),
                'jobContents' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('type_description_en', $this->type_description_en, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}