<?php

/**
 * This is the model base class for the table "province".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Province".
 *
 * Columns in table "province" available as properties of the model,
 * followed by relations of table "province" available as properties of the model.
 *
 * @property integer $id
 * @property string $province_name_lo
 * @property string $province_name_en
 * @property string $province_code
 *
 * @property Coor[] $coors
 * @property Cv[] $cvs
 * @property Cv[] $cvs1
 * @property JobContent[] $jobContents
 */
abstract class BaseProvince extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'province';
    }

    public static function representingColumn() {
        return 'province_name_lo';
    }

    public function rules() {
        return array(
            array('province_name_lo, province_name_en, province_code', 'required'),
            array('province_name_lo, province_name_en', 'length', 'max'=>45),
            array('province_code', 'length', 'max'=>5),
            array('id, province_name_lo, province_name_en, province_code', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'coors' => array(self::HAS_MANY, 'Coor', 'province_id'),
            'cvs' => array(self::HAS_MANY, 'Cv', 'province_id'),
            'cvs1' => array(self::MANY_MANY, 'Cv', 'cv_has_province(province_id, cv_id)'),
            'jobContents' => array(self::HAS_MANY, 'JobContent', 'province_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'province_name_lo' => Yii::t('app', 'Province Name Lo'),
                'province_name_en' => Yii::t('app', 'Province Name En'),
                'province_code' => Yii::t('app', 'Province Code'),
                'coors' => null,
                'cvs' => null,
                'cvs1' => null,
                'jobContents' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('province_name_lo', $this->province_name_lo, true);
        $criteria->compare('province_name_en', $this->province_name_en, true);
        $criteria->compare('province_code', $this->province_code, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}