<?php

/**
 * This is the model base class for the table "menu".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Menu".
 *
 * Columns in table "menu" available as properties of the model,
 * followed by relations of table "menu" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $link
 * @property string $show
 * @property string $section
 * @property string $order_no
 * @property string $content
 * @property string $widget
 *
 * @property MenuSub[] $menuSubs
 * @property MenuTranslate[] $menuTranslates
 */
abstract class BaseMenu extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'menu';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name, show, section', 'required'),
            array('name, link, widget', 'length', 'max'=>255),
            array('show', 'length', 'max'=>3),
            array('section', 'length', 'max'=>6),
            array('order_no', 'length', 'max'=>5),
            array('content', 'safe'),
            array('link, order_no, content, widget', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, link, show, section, order_no, content, widget', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'menuSubs' => array(self::HAS_MANY, 'MenuSub', 'menu_id'),
            'menuTranslates' => array(self::HAS_MANY, 'MenuTranslate', 'menu_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Name'),
                'link' => Yii::t('app', 'Link'),
                'show' => Yii::t('app', 'Show'),
                'section' => Yii::t('app', 'Section'),
                'order_no' => Yii::t('app', 'Order No'),
                'content' => Yii::t('app', 'Content'),
                'widget' => Yii::t('app', 'Widget'),
                'menuSubs' => null,
                'menuTranslates' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('link', $this->link, true);
        $criteria->compare('show', $this->show, true);
        $criteria->compare('section', $this->section, true);
        $criteria->compare('order_no', $this->order_no, true);
        $criteria->compare('content', $this->content, true);
        $criteria->compare('widget', $this->widget, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}