<?php

/**
 * This is the model base class for the table "widget".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Widget".
 *
 * Columns in table "widget" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property string $content
 * @property string $order_no
 * @property string $is_show
 *
 */
abstract class BaseWidget extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'widget';
    }

    public static function representingColumn() {
        return 'name';
    }

    public function rules() {
        return array(
            array('name, title, content', 'required'),
            array('name, title', 'length', 'max'=>255),
            array('order_no', 'length', 'max'=>1),
            array('is_show', 'length', 'max'=>3),
            array('order_no, is_show', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, title, content, order_no, is_show', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'name' => Yii::t('app', 'Name'),
                'title' => Yii::t('app', 'Title'),
                'content' => Yii::t('app', 'Content'),
                'order_no' => Yii::t('app', 'Order No'),
                'is_show' => Yii::t('app', 'Is Show'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('content', $this->content, true);
        $criteria->compare('order_no', $this->order_no, true);
        $criteria->compare('is_show', $this->is_show, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}